version: '2'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: shephik/devops-for-programmers-project-74  
    command: npm test

  production:
    build:
      context: .
      dockerfile: Dockerfile