version: '2'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: shephik/devops-for-programmers-project-74  
    volumes:
      - "./app/.env.example:/app/.env"
    command: npm test  
    depends_on:
      - db 

  production:
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:latest
    restart: always
    # env_file:
    #   - ./app/.env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password" 