name: build-app

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-node@v4
        with: 
          node-version: '14.18.1'
          cache: npm
          
      - run: make ci
      - run: make test
      - run: make docker-build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - run: make docker-push       

